# syntax version.
# services list.
services:
  # base image
  alpine-base:
    image: "reinanhs/limarka:${LIMARKA_VERSION}-alpine-v${ALPINE_VERSION}-base"
    build:
      context: "alpine/base"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
  test-alpine-base:
    image: "reinanhs/limarka:${LIMARKA_VERSION}-alpine-v${ALPINE_VERSION}-base"
    entrypoint: "sh -c 'sh exec-test.sh'"
    volumes:
      - ./tests:/trabalho
