# syntax version.
version: "3.7"

# services list.
services:
  # base image
  alpine-base:
    image: "reinanhs/limarka:alpine-v${ALPINE_VERSION}-base"
    build:
      context: "alpine/base"
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
